// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Nurzhanat Zhussup",
            "url": "https://github.com/nzhussup"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/llm/configuration": {
            "get": {
                "description": "Returns active runtime LLM settings such as model, prompts, and parallel generation flag.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configuration"
                ],
                "summary": "Get current LLM configuration",
                "responses": {
                    "200": {
                        "description": "Current configuration",
                        "schema": {
                            "$ref": "#/definitions/dto.ConfigurationResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Updates runtime LLM settings such as model, prompts, and parallel generation flag.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configuration"
                ],
                "summary": "Update LLM configuration",
                "parameters": [
                    {
                        "description": "Configuration overrides",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ConfigurationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated configuration",
                        "schema": {
                            "$ref": "#/definitions/dto.ConfigurationResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid configuration payload",
                        "schema": {
                            "$ref": "#/definitions/dto.APIResponse"
                        }
                    }
                }
            }
        },
        "/v1/llm/health": {
            "get": {
                "description": "Checks the connectivity and health of dependent services, particularly Redis.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check endpoint",
                "responses": {
                    "200": {
                        "description": "Status OK",
                        "schema": {
                            "$ref": "#/definitions/dto.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Redis connection failed",
                        "schema": {
                            "$ref": "#/definitions/dto.APIResponse"
                        }
                    }
                }
            }
        },
        "/v1/llm/summarize": {
            "get": {
                "description": "Retrieves structured personal data (e.g., work experience, education), generates a professional summary using a large language model (LLM), and returns it in the requested language.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "summarizer"
                ],
                "summary": "Generate professional profile summary",
                "parameters": [
                    {
                        "type": "string",
                        "name": "lang",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Generated professional summary",
                        "schema": {
                            "$ref": "#/definitions/dto.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid query parameters",
                        "schema": {
                            "$ref": "#/definitions/dto.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error with error details",
                        "schema": {
                            "$ref": "#/definitions/dto.APIResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.APIResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "dto.ConfigurationRequest": {
            "type": "object",
            "properties": {
                "enable_parallel_generation": {
                    "type": "boolean"
                },
                "model": {
                    "type": "string"
                },
                "system_prompt_de": {
                    "type": "string"
                },
                "system_prompt_en": {
                    "type": "string"
                },
                "system_prompt_kz": {
                    "type": "string"
                }
            }
        },
        "dto.ConfigurationResponse": {
            "type": "object",
            "properties": {
                "enable_parallel_generation": {
                    "type": "boolean"
                },
                "model": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "system_prompt_de": {
                    "type": "string"
                },
                "system_prompt_en": {
                    "type": "string"
                },
                "system_prompt_kz": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8086",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Summarizer Service API",
	Description:      "This is the API for generating summary from user profile data.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
