#!/bin/sh

set -eu

: "${NGINX_GATEWAY_LISTEN_PORT:=8082}"
: "${NGINX_GATEWAY_BASE_UPSTREAM_HOST:=base-service}"
: "${NGINX_GATEWAY_BASE_UPSTREAM_PORT:=8010}"
: "${NGINX_GATEWAY_IMAGE_UPSTREAM_HOST:=image-service}"
: "${NGINX_GATEWAY_IMAGE_UPSTREAM_PORT:=8085}"
: "${NGINX_GATEWAY_LLM_UPSTREAM_HOST:=llm-service}"
: "${NGINX_GATEWAY_LLM_UPSTREAM_PORT:=8086}"
: "${NGINX_GATEWAY_ACCOUNT_UPSTREAM_HOST:=account-service}"
: "${NGINX_GATEWAY_ACCOUNT_UPSTREAM_PORT:=8087}"

envsubst '${NGINX_GATEWAY_LISTEN_PORT} ${NGINX_GATEWAY_BASE_UPSTREAM_HOST} ${NGINX_GATEWAY_BASE_UPSTREAM_PORT} ${NGINX_GATEWAY_IMAGE_UPSTREAM_HOST} ${NGINX_GATEWAY_IMAGE_UPSTREAM_PORT} ${NGINX_GATEWAY_LLM_UPSTREAM_HOST} ${NGINX_GATEWAY_LLM_UPSTREAM_PORT} ${NGINX_GATEWAY_ACCOUNT_UPSTREAM_HOST} ${NGINX_GATEWAY_ACCOUNT_UPSTREAM_PORT}' \
  < /etc/nginx/templates/nginx.conf.template \
  > /etc/nginx/nginx.conf

exec nginx -g 'daemon off;'
