---
openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
paths:
  "/v1/user/public":
    put:
      tags:
      - public-user-controller
      operationId: updateUser
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/User"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: object
    post:
      tags:
      - public-user-controller
      operationId: registerUser
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/PublicUserRegistryRequest"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: object
    delete:
      tags:
      - public-user-controller
      operationId: deleteUser
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/User"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: object
  "/v1/user/admin":
    get:
      tags:
      - admin-user-controller
      operationId: findAll
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/User"
    put:
      tags:
      - admin-user-controller
      operationId: updateUser_1
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/User"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: object
    post:
      tags:
      - admin-user-controller
      operationId: registerUser_1
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/AdminUserRegistryRequest"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: object
    delete:
      tags:
      - admin-user-controller
      operationId: deleteUser_1
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/User"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: object
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        password:
          type: string
        role:
          type: string
    PublicUserRegistryRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    AdminUserRegistryRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        role:
          type: string
